import type { Metadata } from "next";
import { Gorditas, Inter } from "next/font/google";
import "./globals.css";

const gorditas = Gorditas({
  weight: ["400"],
  variable: "--font-gorditas",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${gorditas.variable} ${inter.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
